# Generated by Django 4.0.2 on 2022-08-21 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('processnlp', '0003_alter_nlpmodel_processing_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nlpmodel',
            name='processing_time',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=7, null=True, verbose_name='Processing time'),
        ),
    ]
